### PR TITLE
Add layout support

### PR DESCRIPTION
**Pull request by tsu1980**
Fix #38 BC problem.

### CODE REVIEW

**Comment by geggleto** [comment]
@akrabat this is fine to merge; but we should update the travis to allow failures on HHVM

**Comment by geggleto** [comment]
@tsu1980 can you merge master into your branch. Should clear up the travis error. thanks.

**Comment by tsu1980** [comment]
@geggleto Done!

**Comment by piotr-cz** [comment]
There is a problem when using the `fetch` method directly and layout is set.
Application crashes with an error 
```
Fatal error: Uncaught Error: Maximum function nesting level of '512' reached, aborting! 
```

See https://github.com/slimphp/PHP-View/issues/49#issuecomment-519986193

**Pull request merged**
